#!/bin/bash
export TERM=xterm-color

NC='\033[0m' # No Color
RED='\033[0;31m'
LIGHTGREEN='\033[1;32m'
CYAN='\033[0;36m'
LIGHTYELLOW='\033[1;33m'
bold=$(tput bold)
normal=$(tput sgr0)

echo '----------------------------------------'
echo -e ${CYAN}${bold}'UPDATING THE SYSTEM:'${normal}${LIGHTYELLOW}
echo '----------------------------------------'

sudo apt-get -y update


sleep 3
echo '----------------------------------------'
echo -e ${CYAN}${bold}'INSTALLING PHPMYADMIN:'${normal}${LIGHTYELLOW}
echo '----------------------------------------'

apt-get install pwgen -y

MYSQL_ROOT_PASS="my_sql_root_pass" # Put yours

PHPMYADMIN_DIR="myphpdir"      # You don't want script kiddies playing  
                                   # with your default phpMyAdmin install.
AUTOGENERATED_PASS=`pwgen -c -1 20`

echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections

apt-get -y install phpmyadmin php-mbstring php-gettext

# Regex FTW!
sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf

sudo phpenmod mcrypt
sudo phpenmod mbstring


sleep 3
echo '----------------------------------------'
echo -e ${CYAN}${bold}'INSTALLING PHPMYADMIN:'${normal}${LIGHTYELLOW}
echo '----------------------------------------'

sudo apt-get install phpmyadmin php-mbstring php-gettext